#!/bin/sh
if [ -z $1 ]; then
	echo "$0 <file> generates hex file (with suffix .padded.hex),  that is padded and ready for Funky FOTA"
	exit
fi
echo Padding $1 to 128 to be allign with SPM_PAGESIZE
SZ=$(srec_cat $1 -intel -o - -bin | wc -c)
SZAPP=14336
SZANDLENGTH=$(($SZ + 2))
if [ $SZANDLENGTH -gt $SZAPP ] ; then
        echo $1 is too big, remove: $(( $SZANDLENGTH - $SZAPP)) bytes
        ls -la $1
        exit
else
        echo We have space for: $(($SZAPP-$SZANDLENGTH)) bytes.
fi

#store size of $1 into len.hex
srec_cat -generate 0x000 0x002 -l-e-constant $SZ 2 -o len.hex -intel
#concatenate len.hex and $1 
srec_cat len.hex -intel $1 -intel -offset 0x2 -o len.hex -intel
#enforce padding to SPM_PAGESIZE
srec_cat len.hex -intel -fill 0xFF -within len.hex -intel -range-padding 128 -o len.hex -intel -Line_Length 44
#skip first line that is generated by srec_cat in padding mode
tail -n+2 len.hex > $1.padded.hex
